#----- GDSC-HyperTribe Pipeline Configuration File -----#     
#-------------------------------------------------------#


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# GENERAL SETTINGS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Comma-delimited file with four columns: Sample_ID,fastq_1,fastq_2,replicate (case-sensitive)
# replicate must be an integer
sample_csv: "sample_fastq_list_single.txt"
experimentName: "test"
layout: "paired"
refSample: "DCD"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# REPLICATES
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#replicateNames: [1,2,3]

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# (NO CONDA) SOFTWARE PATHS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
trimmomatic_jar: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/shared-software/tools/trimmomatic/Trimmomatic-0.39/trimmomatic-0.39.jar"
picard_jar: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/shared-software/tools/picard/picard.jar"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# TRIMMING AND ALIGNMENT SETTINGS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
avgquality: "25"
starIndex: "/dartfs/rc/nosnapshots/G/GMBSR_refs/Mmusculus/GRCm39/rna_index/STAR_index/GRCm39.primary_assembly.genome"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# RNA-EDIT SITE PARAMETERS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#annotationFile: "annotations/refFlat.txt"
annotationFile: "/dartfs/rc/nosnapshots/G/GMBSR_refs/Mmusculus/GRCm39/annotation/picard/GRCm39.primary_Assembly.genome.refFlat"
wtRNA_tableName: "DCD"
timepoint: "2"
wtTimepoint: "1"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# FILTERING PARAMETERS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
fivePercentEditThreshold: "5"
onePercentEditThreshold: "1"
readThreshold: "20"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# UTILITY SCRIPTS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
samToMatrixScript: "CODE/sam_to_matrix.pl"
loadMatrix: "CODE/load_matrix_data.pl"
diagnoseDatabase: "CODE/diagnose_mysql_table.pl"
findRNA: "CODE/find_rnaeditsites.pl"
bedgraphScript: "CODE/convert_editsites_to_bedgraph.py"
filterScript: "CODE/filter_by_threshold_without_header.pl"
summaryScript: "CODE/summarize_results.pl"