#----- GDSC-HyperTribe Pipeline Configuration File -----#     
#-------------------------------------------------------#


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# GENERAL SETTINGS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Comma-delimited file with four columns: Sample_ID,fastq_1,fastq_2,replicate (case-sensitive)
# replicate must be an integer
sample_csv: "sample_fastq_list_single.txt"
experimentName: "test"
layout: "paired"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# (NO CONDA) SOFTWARE PATHS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
trimmomatic_jar: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/shared-software/tools/trimmomatic/Trimmomatic-0.39/trimmomatic-0.39.jar"
picard_jar: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/shared-software/tools/picard/picard.jar"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# TRIMMING AND ALIGNMENT SETTINGS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
avgquality: "25"
starIndex: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/shared-software/workflows/hypertribe/HyperTRIBE/annotations/star_indices"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# UTILITY SCRIPTS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
samToMatrixScript: "CODE/sam_to_matrix.pl"
loadMatrix: "CODE/load_matrix_data.pl"
diagnoseDatabase: "CODE/diagnose_mysql_table.pl"